apiVersion: v1
kind: Service
metadata:
  name: a3data-challenge-service
spec:
  selector:
    app: a3data-challenge-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
